### PR TITLE
Allow configUri to be passed from deploy steps

### PR DESCRIPTION
**Pull request by zephraph**
Requested by @izakp.

This PR allows the deploy step to provide the configUri parameter to the `configure-hokusai` job.

Passing down params is a little cumbersome without making a breaking change. You either have to hoist the default _or_ do something like I did here....

Essentially, to keep the default for `configUri` contained in `configure-hokusai` I modified `configure-hokusai` to check for an empty string. When it's not empty, it'll use the parameter. When it is, it uses a hard coded default. 

If someone can think of a better way of doing this w/o introducing a breaking change I'm all ears.

### CODE REVIEW

**Review by eessex — APPROVED** [review]
👍

**Comment by izakp** [comment]
LGTM - thanks @zephraph

**Review by izakp — APPROVED** [review]
This isn't going to be strictly necessary for our k8s 1.18 migration but still good to have so we can test a new hokusai configuration (i.e. updated kubectl version and config file)

**Comment by eessex** [comment]
This change will require us to make a code change in each repo we want to point to the new url for. I wonder if it wouldn't be better to leave this hardcoded, but upgrade the orb with a major version. This would prevent apps from auto-merging the orb, but allow us to upgrade without PRs to individual repos.

**Comment by zephraph** [comment]
> This change will require us to make a code change in each repo we want to point to the new url for

It would, but it uses the default by default. Is this something you expect to be a broader change that multiple repositories will need? At that point maybe thinking about adding environment variable support makes sense.

**Comment by zephraph** [comment]
Okay, I think this last update will cover your case better. You can pass the config path via a parameter in the job and that'll take precedence. If you _want_ to use an environment variable, you can do that by populating `HOKUSAI_CONFIG_PATH`. If you don't supply either of those, it'll keep the normal default.

**Comment by izakp** [comment]
@zephraph can we block this behind a version update for the hokusai and remote docker orbs?  Need to get CI up to date with version 0.5.13 (so this would make the orb version here 0.7.8)

**Pull request closed without merging**
